### ISSUE TITLE
Registration policy for units

### ISSUE THREAD

**Issue by akeranen** [core-wg/senml-spec#77]
From Peter's review:
>>  New entries can be added to the registration by either Expert Review
  or IESG Approval as defined in [RFC5226].

> Why define two policies? That's just introducing the possibility of
confusion.

**Comment by fluffy** [comment]
It means that if something needs to happen and AD can make it happen without firing the expert which creates so much bad will that an AD would much rather wit 6 months for the expert to respond. All it says if the AD can do this or the expert can. I don't care much.

**Comment by akeranen** [comment]
@fluffy Our AD had preference to have just Expert review in order for people to not think there are two paths but show clear preference. If things are slow, the IESG is next on the appeal path, so ADs can do it anyway.

**Comment by akeranen** [comment]
Addressed by PR #80

**Comment by cabo** [comment]
Note that even with #80 we still have the dual policy on the labels.  Bug or feature?

**Comment by fluffy** [comment]
On the "Our AD had preference to have just Expert review " ... I'm fine with this.

**Comment by akeranen** [comment]
@cabo The dual policy was fixed with the latest commit. Although perhaps we want to have more guidelines for the expert to follow?
